#!/bin/bash
rm -fv *-Vanadium-branding.patch
rm -fv *-Vanadium-branding-for-WebView.patch
rm -fv *-Vanadium-string-rebranding.patch
rm -fv *-redirect-settings-help-icon.patch
rm -fv *-remove-Google-prefix-from-storage-settings-label.patch
rm -fv *-add-back-trichrome_chrome_apk-targets.patch
rm -fv *-add-trichrome-browser-apk-targets.patch
rm -fv *-update-trichrome_library_apk-expectation-file.patch
rm -fv *-update-dependencies.patch
rm -fv *-Rolling-all-public-GMSCore-libraries.patch
rm -fv *-Clean-up-logic-in-BuildInfo.targetsAtLeastT.patch
rm -fv *-Update-to-Android-T-SDK.patch
rm -fv *-set-original-package-to-org.chromium.chrome.patch
rm -fv *-Support-for-extended-version-name-and-increments.patch
rm -fv *-use-vanadium.app-for-component-updates.patch
rm -fv *-use-grapheneos.network-when-verifying-DNS-over-HTTPS.patch
rm -fv *-Android-U-Add-SDK-34-packages-to-CIPD.patch
rm -fv *-Make-compile_resources-only-use-main-Android-SDK-jar.patch
rm -fv *-Android-U-Deleting-line-in-test-asserting-we-aren-t-.patch
rm -fv *-Android-U-rolling-DEPS-entries-to-start-using-Androi.patch
rm -fv *-Use-GrapheneOS-connectivity-check-as-well-for-Help-a.patch
rm -fv *-Add-support-to-forcibly-override-minimum-sdk-version.patch
rm -fv *-Checkout-PGO-profiles.patch
###
rm -fv *-Add-an-easily-extensible-way-to-reference-targets-ea.patch
rm -fv *-Add-a-new-config-like-apk-target-for-building.patch
rm -fv *-config-Directly-reference-config-apk-build-target.patch
rm -fv *-config-Generate-ConfigInfo-from-config-apk.patch
rm -fv *-config-Provide-targets-for-linking-and-inclusion-of-.patch
rm -fv *-config-Include-the-ConfigInfo-class-for-Monochrome-a.patch
rm -fv *-config-Include-the-ConfigInfo-class-for-WebView-targ.patch
rm -fv *-config-test-Add-ConfigInfo-on-necessary-integration-.patch
rm -fv *-config-Add-proto-definitions-for-feature-flags-and-o.patch
rm -fv *-config-Add-protobuf-generator-parser-for-config-apk-.patch
rm -fv *-config-Initial-configuration-for-config-apk.patch
rm -fv *-config-Add-config-parser-for-browser-and-webview.patch
rm -fv *-config-Helper-script-for-fetching-content-filtering-.patch
rm -fv *-config-add-new-needed-deps-to-fetch-filter-lists.patch
rm -fv *-config-Build-target-for-android-assets-including-the.patch
rm -fv *-config-Build-target-for-android-assets-for-config-fi.patch
rm -fv *-config-Add-the-needed-component-and-protobuf-file-fo.patch
rm -fv *-Extension-of-build-system-for-java-files-in-base-lay.patch
rm -fv *-Add-hooks-for-LibraryLoader-on-early-initialization-.patch
rm -fv *-Add-hooks-for-initializing-contents-of-VanadiumConfi.patch
rm -fv *-Extension-of-build-system-at-android-specific-subres.patch
rm -fv *-Expose-fetching-config-state-for-content-filtering-t.patch
rm -fv *-Use-ruleset-from-config-apk-whenever-it-s-present.patch
rm -fv *-Add-update-handling-of-subresource-filter-component-.patch
rm -fv *-Extension-of-build-system-for-static-library-deps-at.patch
rm -fv *-Update-subresource-filter-from-config-apk.patch
rm -fv *-Use-the-content-filtering-from-config-app-when-avail.patch
rm -fv *-subresource-filter-rules-version-on-about-Vanadium-s.patch
rm -fv *-don-t-show-subresource-filter-UI-for-site.patch
rm -fv *-enable-subresource-filter-on-all-sites.patch
rm -fv *-Use-the-old-naming-convention-of-Ads-in-ads-site-set.patch
rm -fv *-Always-enable-CredentialManager-APIs-for-all-apps.patch
rm -fv *-Skip-checks-for-android-autofill-service-app-when-us.patch
rm -fv *-config-generator-Initial-configuration-for-config-ap.patch
rm -fv *-config-parser-Add-config-parser-for-browser-and-webv.patch
rm -fv *-filter-lists-Helper-script-for-fetching-content-filt.patch
rm -fv *-Add-hooks-for-applying-flags-features-at-runtime.patch
rm -fv *-content-filtering-Add-update-handling-of-subresource.patch
rm -fv *-config-generator-Always-enable-CredentialManager-API.patch
rm -fv *-Enable-CredentialManager-APIs-for-all-apps-supportin.patch
rm -fv *-Add-support-for-calling-added-APIs-from-custom-OS.patch
rm -fv *-filter-lists-Update-script-to-also-include-saving-sh.patch
rm -fv *-config-Remove-support-for-broadcast-receiver-for-fet.patch
rm -fv *-config-generator-Skip-checks-for-android-autofill-se.patch
rm -fv *-config-parser-Add-support-for-conditional-parsing-of.patch
rm -fv *-config-Add-new-definitions-for-additional-components.patch
rm -fv *-config-Add-support-for-generating-configs-with-addit.patch
rm -fv *-config-parser-add-support-for-parsing-conditional-co.patch
rm -fv *-Add-a-method-to-hook-at-Application.attachBaseContex.patch
rm -fv *-Add-hooks-for-ChromeApplicationImpl-to-initialize-co.patch
rm -fv *-content-filtering-Add-support-for-updating-content-f.patch
rm -fv *-Add-support-for-conditional-content-filtering-compon.patch
rm -fv *-add-support-for-german-specific-langauge-content-fil.patch
rm -fv *-temp-config-generator-Forcibly-skip-checks-for-andro.patch
rm -fv *-temp-config-generator-Forcibly-disable-translate-opt.patch
rm -fv *-temporary-config-disable-conditional-component-if-de.patch
rm -fv *-Update-Resources-and-Configuration-generated-protobu.patch
rm -fv *-Document-more-needed-removals-for-protobuf.patch
rm -fv *-Android-V-Add-SDK-35-packages-to-CIPD.patch
rm -fv *-Android-V-rolling-DEPS-entries-to-start-using-Androi.patch
rm -fv *-tmp-config-generator-Backport-WebView-context-leak-f.patch
rm -fv *-Include-a-java-port-of-atomic-file-and-scoped-file-d.patch
rm -fv *-Add-support-for-upstream-file-based-parsing-of-unind.patch
rm -fv *-fixup-Expose-fetching-config-state-for-content-filte.patch
rm -fv *-fixup-Use-ruleset-from-config-apk-whenever-it-s-pres.patch
rm -fv *-fixup-content-filtering-Add-update-handling-of-subre.patch
rm -fv *-fixup-Use-the-content-filtering-from-config-app-when.patch
rm -fv *-Use-64-bit-toolchain-by-default-for-generating-resou.patch
rm -fv *-enable-stack-clash-protection-for-arm64-targets.patch
rm -fv *-Always-start-child-processes-in-jitless-mode-when-ex.patch
rm -fv *-Use-fstack-protector-strong-with-shadow-call-stack-w.patch
rm -fv *-config-Explicitly-declare-queries-to-config-package-.patch
rm -fv *-add-support-for-german-specific-language-content-fil.patch
rm -fv *-config-Compile-the-config-holder-app-with-forceQuery.patch
rm -fv *-Reduce-user-agent-and-client-hints-for-webview.patch
rm -fv *-config-disable-domain-reliability-feature.patch
rm -fv *-config-Disable-fullscreen-exit-callback-for-picture-.patch
rm -fv *-tmp-Disable-usage-of-new-checkServerTrusted-API-for-
